name: Run OPA Tests
on:
  workflow_call:
    inputs:
      path:
        description: "OPA review"
        required: true
        type: string
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test ${{ inputs.path }}/*.rego -v


    - name: Run OPA Eval
      run: opa eval --data terraform.security.rego  
